### ISSUE TITLE
这个报错怎么解决

### ISSUE THREAD

**Issue by xunlongdingxue** [wuwen1030/oclint_argument_list_too_long_solution#5]
Traceback (most recent call last):
  File "/Users/lichangqing/Desktop/未命名文件夹/oclint.py", line 116, in <module>
    combine_outputs(xml_files)
  File "/Users/lichangqing/Desktop/未命名文件夹/oclint.py", line 83, in combine_outputs
    base_tree = ET.ElementTree(file=output_files[0])
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 540, in __init__
    self.parse(file)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'oclint00.xml'

**Comment by Coder-Star** [comment]
> Traceback (most recent call last): File "/Users/lichangqing/Desktop/未命名文件夹/oclint.py", line 116, in combine_outputs(xml_files) File "/Users/lichangqing/Desktop/未命名文件夹/oclint.py", line 83, in combine_outputs base_tree = ET.ElementTree(file=output_files[0]) File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 540, in **init** self.parse(file) File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse source = open(source, "rb") FileNotFoundError: [Errno 2] No such file or directory: 'oclint00.xml'

有解决吗？
